import type { LucideIcon } from "lucide-react";
import {
  Apple,
  Armchair,
  ArrowLeftRight,
  Baby,
  Banknote,
  Bath,
  Bed,
  Beer,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Bus,
  Calculator,
  Calendar,
  Camera,
  Car,
  CarTaxiFront,
  Church,
  CircleDollarSign,
  CircleParking,
  Cloud,
  Coffee,
  Coins,
  Cookie,
  CreditCard,
  Cross,
  CupSoda,
  Dog,
  Droplets,
  Dumbbell,
  FileText,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HandCoins,
  Handshake,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  Hospital,
  Hotel,
  IceCreamCone,
  KeyRound,
  Landmark,
  Laptop,
  Library,
  Luggage,
  Mail,
  MapPin,
  Mic,
  Monitor,
  Mountain,
  Music,
  Package,
  PartyPopper,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Printer,
  Puzzle,
  QrCode,
  Receipt,
  Repeat,
  Salad,
  Sandwich,
  Scale,
  School,
  Scissors,
  Settings,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Tag,
  Tent,
  Ticket,
  TrainFront,
  Trees,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Users,
  UtensilsCrossed,
  Video,
  Wallet,
  Watch,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

export const PALETA_CATEGORIA = [
  "neutro",
  "gelo",
  "ardosia",
  "grafite",
  "azul",
  "azul-royal",
  "anil",
  "ciano",
  "turquesa",
  "menta",
  "verde",
  "lima",
  "oliva",
  "ambar",
  "ouro",
  "laranja",
  "pessego",
  "coral",
  "vermelho",
  "rosa",
  "magenta",
  "violeta",
  "vinho",
  "marrom",
] as const;

export type CorCategoria = (typeof PALETA_CATEGORIA)[number];

const CATALOGO_ICONE = [
  { slug: "geral", rotulo: "Geral", Icone: Tag },
  { slug: "tag", rotulo: "Tag", Icone: Tag },
  { slug: "restaurante", rotulo: "Restaurante", Icone: UtensilsCrossed },
  { slug: "mercado", rotulo: "Mercado", Icone: ShoppingCart },
  { slug: "cafe", rotulo: "Café", Icone: Coffee },
  { slug: "pizza", rotulo: "Pizza", Icone: Pizza },
  { slug: "lanche", rotulo: "Lanche", Icone: Sandwich },
  { slug: "salada", rotulo: "Salada", Icone: Salad },
  { slug: "fruta", rotulo: "Fruta", Icone: Apple },
  { slug: "padaria", rotulo: "Padaria", Icone: Cookie },
  { slug: "sorvete", rotulo: "Sorvete", Icone: IceCreamCone },
  { slug: "cerveja", rotulo: "Cerveja", Icone: Beer },
  { slug: "vinho", rotulo: "Vinho", Icone: Wine },
  { slug: "bebida", rotulo: "Bebida", Icone: CupSoda },
  { slug: "casa", rotulo: "Casa", Icone: Home },
  { slug: "luz", rotulo: "Luz", Icone: Zap },
  { slug: "agua", rotulo: "Água", Icone: Droplets },
  { slug: "gas", rotulo: "Gás", Icone: Flame },
  { slug: "internet", rotulo: "Internet", Icone: Wifi },
  { slug: "telefone", rotulo: "Telefone", Icone: Phone },
  { slug: "moveis", rotulo: "Móveis", Icone: Armchair },
  { slug: "sofa", rotulo: "Sofá", Icone: Sofa },
  { slug: "cama", rotulo: "Cama", Icone: Bed },
  { slug: "banho", rotulo: "Banho", Icone: Bath },
  { slug: "limpeza", rotulo: "Limpeza", Icone: Sparkles },
  { slug: "conserto", rotulo: "Conserto", Icone: Wrench },
  { slug: "ferramenta", rotulo: "Ferramenta", Icone: Hammer },
  { slug: "chave", rotulo: "Chave", Icone: KeyRound },
  { slug: "carro", rotulo: "Carro", Icone: Car },
  { slug: "combustivel", rotulo: "Combustível", Icone: Fuel },
  { slug: "taxi", rotulo: "Táxi", Icone: CarTaxiFront },
  { slug: "onibus", rotulo: "Ônibus", Icone: Bus },
  { slug: "metro", rotulo: "Metrô", Icone: TrainFront },
  { slug: "bike", rotulo: "Bicicleta", Icone: Bike },
  { slug: "estacionamento", rotulo: "Estacionamento", Icone: CircleParking },
  { slug: "navio", rotulo: "Navio", Icone: Ship },
  { slug: "viagem", rotulo: "Viagem", Icone: Plane },
  { slug: "hotel", rotulo: "Hotel", Icone: Hotel },
  { slug: "mala", rotulo: "Mala", Icone: Luggage },
  { slug: "camping", rotulo: "Camping", Icone: Tent },
  { slug: "montanha", rotulo: "Montanha", Icone: Mountain },
  { slug: "saude", rotulo: "Saúde", Icone: HeartPulse },
  { slug: "farmacia", rotulo: "Farmácia", Icone: Pill },
  { slug: "hospital", rotulo: "Hospital", Icone: Hospital },
  { slug: "consulta", rotulo: "Consulta", Icone: Stethoscope },
  { slug: "vacina", rotulo: "Vacina", Icone: Syringe },
  { slug: "academia", rotulo: "Academia", Icone: Dumbbell },
  { slug: "mente", rotulo: "Mente", Icone: Brain },
  { slug: "cruz", rotulo: "Cruz", Icone: Cross },
  { slug: "streaming", rotulo: "Streaming", Icone: Tv },
  { slug: "musica", rotulo: "Música", Icone: Music },
  { slug: "cinema", rotulo: "Cinema", Icone: Film },
  { slug: "video", rotulo: "Vídeo", Icone: Video },
  { slug: "jogos", rotulo: "Jogos", Icone: Gamepad2 },
  { slug: "livro", rotulo: "Livro", Icone: BookOpen },
  { slug: "festa", rotulo: "Festa", Icone: PartyPopper },
  { slug: "ingresso", rotulo: "Ingresso", Icone: Ticket },
  { slug: "microfone", rotulo: "Microfone", Icone: Mic },
  { slug: "fone", rotulo: "Fone", Icone: Headphones },
  { slug: "salario", rotulo: "Salário", Icone: Wallet },
  { slug: "poupanca", rotulo: "Poupança", Icone: PiggyBank },
  { slug: "investimento", rotulo: "Investimento", Icone: CircleDollarSign },
  { slug: "pix", rotulo: "Pix", Icone: QrCode },
  { slug: "transferencia", rotulo: "Transferência", Icone: ArrowLeftRight },
  { slug: "moedas", rotulo: "Moedas", Icone: Coins },
  { slug: "dinheiro", rotulo: "Dinheiro", Icone: Banknote },
  { slug: "banco", rotulo: "Banco", Icone: Building2 },
  { slug: "fatura", rotulo: "Fatura", Icone: CreditCard },
  { slug: "emprestimo", rotulo: "Empréstimo", Icone: HandCoins },
  { slug: "seguro", rotulo: "Seguro", Icone: Shield },
  { slug: "calculadora", rotulo: "Calculadora", Icone: Calculator },
  { slug: "vendas", rotulo: "Vendas", Icone: Receipt },
  { slug: "servicos", rotulo: "Serviços", Icone: Briefcase },
  { slug: "trabalho", rotulo: "Trabalho", Icone: Handshake },
  { slug: "notebook", rotulo: "Notebook", Icone: Laptop },
  { slug: "monitor", rotulo: "Monitor", Icone: Monitor },
  { slug: "educacao", rotulo: "Educação", Icone: GraduationCap },
  { slug: "escola", rotulo: "Escola", Icone: School },
  { slug: "biblioteca", rotulo: "Biblioteca", Icone: Library },
  { slug: "impostos", rotulo: "Impostos", Icone: Landmark },
  { slug: "documento", rotulo: "Documento", Icone: FileText },
  { slug: "justica", rotulo: "Justiça", Icone: Gavel },
  { slug: "balanca", rotulo: "Balança", Icone: Scale },
  { slug: "lazer", rotulo: "Lazer", Icone: ShoppingBag },
  { slug: "loja", rotulo: "Loja", Icone: Store },
  { slug: "roupa", rotulo: "Roupa", Icone: Shirt },
  { slug: "presente", rotulo: "Presente", Icone: Gift },
  { slug: "joia", rotulo: "Joia", Icone: Gem },
  { slug: "relogio", rotulo: "Relógio", Icone: Watch },
  { slug: "corte", rotulo: "Corte", Icone: Scissors },
  { slug: "pet", rotulo: "Pet", Icone: PawPrint },
  { slug: "cachorro", rotulo: "Cachorro", Icone: Dog },
  { slug: "bebe", rotulo: "Bebê", Icone: Baby },
  { slug: "familia", rotulo: "Família", Icone: Users },
  { slug: "coracao", rotulo: "Coração", Icone: Heart },
  { slug: "doacao", rotulo: "Doação", Icone: HeartHandshake },
  { slug: "igreja", rotulo: "Igreja", Icone: Church },
  { slug: "esporte", rotulo: "Esporte", Icone: Trophy },
  { slug: "brinquedo", rotulo: "Brinquedo", Icone: Puzzle },
  { slug: "entrega", rotulo: "Entrega", Icone: Package },
  { slug: "caminhao", rotulo: "Caminhão", Icone: Truck },
  { slug: "jardim", rotulo: "Jardim", Icone: Trees },
  { slug: "sol", rotulo: "Sol", Icone: Sun },
  { slug: "chuva", rotulo: "Chuva", Icone: Umbrella },
  { slug: "celular", rotulo: "Celular", Icone: Smartphone },
  { slug: "camera", rotulo: "Câmera", Icone: Camera },
  { slug: "impressora", rotulo: "Impressora", Icone: Printer },
  { slug: "nuvem", rotulo: "Nuvem", Icone: Cloud },
  { slug: "email", rotulo: "E-mail", Icone: Mail },
  { slug: "mapa", rotulo: "Mapa", Icone: MapPin },
  { slug: "globo", rotulo: "Globo", Icone: Globe },
  { slug: "calendario", rotulo: "Calendário", Icone: Calendar },
  { slug: "recorrente", rotulo: "Recorrente", Icone: Repeat },
  { slug: "configuracao", rotulo: "Configuração", Icone: Settings },
] as const;

export type IconeCategoriaSlug = (typeof CATALOGO_ICONE)[number]["slug"];

export const ICONES_CATEGORIA: readonly IconeCategoriaSlug[] = CATALOGO_ICONE.map((item) => item.slug);

export const ROTULO_ICONE_CATEGORIA = Object.fromEntries(
  CATALOGO_ICONE.map((item) => [item.slug, item.rotulo]),
) as Record<IconeCategoriaSlug, string>;

const ICONE_LUCIDE = Object.fromEntries(CATALOGO_ICONE.map((item) => [item.slug, item.Icone])) as Record<
  IconeCategoriaSlug,
  LucideIcon
>;

const SLUGS_ICONE = new Set<string>(ICONES_CATEGORIA);

export const ROTULO_COR_CATEGORIA: Record<CorCategoria, string> = {
  neutro: "Neutro",
  gelo: "Gelo",
  ardosia: "Ardósia",
  grafite: "Grafite",
  azul: "Azul",
  "azul-royal": "Azul royal",
  anil: "Anil",
  ciano: "Ciano",
  turquesa: "Turquesa",
  menta: "Menta",
  verde: "Verde",
  lima: "Lima",
  oliva: "Oliva",
  ambar: "Âmbar",
  ouro: "Ouro",
  laranja: "Laranja",
  pessego: "Pêssego",
  coral: "Coral",
  vermelho: "Vermelho",
  rosa: "Rosa",
  magenta: "Magenta",
  violeta: "Violeta",
  vinho: "Vinho",
  marrom: "Marrom",
};

const CLASSE_COR: Record<CorCategoria, string> = {
  neutro: "bg-slate-500",
  gelo: "bg-slate-400",
  ardosia: "bg-slate-600",
  grafite: "bg-slate-700",
  azul: "bg-sky-500",
  "azul-royal": "bg-blue-500",
  anil: "bg-indigo-500",
  ciano: "bg-cyan-500",
  turquesa: "bg-teal-500",
  menta: "bg-emerald-400",
  verde: "bg-emerald-500",
  lima: "bg-lime-500",
  oliva: "bg-lime-600",
  ambar: "bg-amber-500",
  ouro: "bg-yellow-500",
  laranja: "bg-orange-500",
  pessego: "bg-orange-400",
  coral: "bg-rose-500",
  vermelho: "bg-red-500",
  rosa: "bg-pink-500",
  magenta: "bg-fuchsia-500",
  violeta: "bg-violet-500",
  vinho: "bg-rose-800",
  marrom: "bg-amber-800",
};

const HEX_COR: Record<CorCategoria, string> = {
  neutro: "#64748b",
  gelo: "#94a3b8",
  ardosia: "#475569",
  grafite: "#334155",
  azul: "#0ea5e9",
  "azul-royal": "#3b82f6",
  anil: "#6366f1",
  ciano: "#06b6d4",
  turquesa: "#14b8a6",
  menta: "#34d399",
  verde: "#10b981",
  lima: "#84cc16",
  oliva: "#65a30d",
  ambar: "#f59e0b",
  ouro: "#eab308",
  laranja: "#f97316",
  pessego: "#fb923c",
  coral: "#f43f5e",
  vermelho: "#ef4444",
  rosa: "#ec4899",
  magenta: "#d946ef",
  violeta: "#8b5cf6",
  vinho: "#9f1239",
  marrom: "#92400e",
};

export function normalizar_icone_categoria(valor: string | null | undefined): IconeCategoriaSlug {
  if (valor && SLUGS_ICONE.has(valor)) {
    return valor as IconeCategoriaSlug;
  }
  return "geral";
}

export function normalizar_cor_categoria(valor: string | null | undefined): CorCategoria {
  if (valor && PALETA_CATEGORIA.includes(valor as CorCategoria)) {
    return valor as CorCategoria;
  }
  return "neutro";
}

export function icone_lucide_categoria(slug: string | null | undefined): LucideIcon {
  return ICONE_LUCIDE[normalizar_icone_categoria(slug)];
}

export function classe_cor_categoria(cor: string | null | undefined): string {
  return CLASSE_COR[normalizar_cor_categoria(cor)];
}

export function hex_cor_categoria(cor: string | null | undefined): string {
  return HEX_COR[normalizar_cor_categoria(cor)];
}
